version: '3.8'

services:
  rclone:
    image: rclone/rclone:latest
    container_name: rclone-sync
    restart: none
    environment:
      - TZ=Europe/Berlin
      - RCLONE_CONFIG_HETZNER_TYPE=crypt
      - RCLONE_CONFIG_HETZNER_REMOTE=${HETZNER_HOST}
      - RCLONE_CONFIG_HETZNER_PASSWORD=${HETZNER_PASS}
      - RCLONE_CONFIG_HETZNER_PASSWORD2=${HETZNER_PASS2}
      - RCLONE_CONFIG_HETZNER_FILENAME_ENCRYPTION=off
      - RCLONE_CONFIG_HETZNER_DIRECTORY_NAME_ENCRYPTION=false
    command: "sync /data HETZNER:/homeoffice-docker-volumes-backup --progress"
    volumes:
      - /volume1/backup-docker-volumes:/data:ro
    # Optional: für Debugging
    stdin_open: true
    tty: true
